### ISSUE TITLE
Feedback - Workshop 14.06.2021

### ISSUE THREAD

**Issue by markusdregi** [equinor/tdd_workshop#13]
Leave feedback as comments during the workshop:

**Comment by sondreso** [comment]
black --version does not work when black is not installed yet. Probably need to run pip install -e . first

**Comment by markusdregi** [comment]
I don't have VSC installed. Does vim suffice, or do I need to install VSC? :)

**Comment by markusdregi** [comment]
Write a comment on Python 3 being used? At least the `python -m venv` is Python 3. Yes, I know 2.7 is EOL, but a lot of OS still ship with python -> python2.7...

**Comment by markusdregi** [comment]
Need GitHub account?

**Comment by kvashchuka** [comment]
Need ssh-key to clone the repository

**Comment by sondreso** [comment]
Think the text on cloning the upstream repo or your own fork (and the renaming of the forks afterwards) could be a bit more clear.

**Comment by hnformentin** [comment]
> I don't have VSC installed. Does vim suffice, or do I need to install VSC? :)

VSC is the recommended tool in Equinor, so we will mostly use it in the workshop. But that is perfect if you are confident with VIM and can follow with it :-)

**Comment by hnformentin** [comment]
> #7
> 
> black --version does not work when black is not installed yet. Probably need to run pip install -e . first

Good point.

**Comment by markusdregi** [comment]
Perhaps it would be good to motivate the participants to spend at least a few iterations on solving the first issue... For instance, strive to do at least 3 iterations of red-green-refactor before you have solved the issue :)
